build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
    environment:
        php:
            version: 5.6.9
checks:
    php:
        code_rating: true
        duplication: true
